gogjango/gjango

main.go, migration.go
=> go-pg migration

main.go, service/user.go
=> Simple implementation of user routes

.gitignore, .vscode/launch.json, controller/account.go, main.go, repository/account/account.go, repository/auth/auth.go, repository/rbac.go, service/account.go, service/auth.go
=> RBAC login implemented, also added to account http service

.gitignore, main.go, model/model.go, model/user.go, repository/auth/auth.go, repository/platform/query/query.go, repository/platform/structs/structs.go, repository/user.go, repository/user/user.go, request/request.go, request/user.go, service/auth.go, service/user.go
=> User crud api

middleware/middleware_test.go
=> middleware_test

.env.sample, config/mail.go, config/postgres.go, config/site.go, mail/mail.go, mock/mockdb/account.go, model/user.go, repository/account.go, repository/auth/auth.go, service/auth.go
=> Send verification email with verification url

.env.sample, config/twilio.go, go.mod, go.sum, main.go, mobile/mobile.go, mock/mobile.go, mock/mockdb/account.go, mock/mockdb/user.go, model/user.go, repository/account.go, repository/auth/auth.go, repository/user.go, request/signup.go, service/auth.go, service/auth_test.go
=> User signup

repository/auth/auth.go, repository/user.go, request/signup.go, service/auth.go
=> Complete mobile verification

mock/mockdb/account.go, model/user.go, repository/account.go, repository/account_integration_test.go, repository/auth/auth.go, service/auth_test.go
=> Get organised and start implementing test for CreateAndVerify

repository/account_integration_test.go
=> AccountRepo CreateAndVerify Test

repository/account.go, repository/account_integration_test.go
=> AccountRepo CreateAndVerify Test, failure case

mock/mockdb/account.go, model/user.go, repository/account.go, repository/account_i_test.go, repository/auth/auth.go, service/auth_test.go
=> Tests for AccountRepo CreateWithMobile

repository/user_i_test.go
=> User tests

repository/rbac_test.go
=> Beginning RBAC tests

mock/mockdb/user.go, model/user.go, repository/auth/auth.go, repository/rbac_test.go, repository/user.go, repository/user/user.go, service/auth_test.go, service/user_test.go
=> Begin integration tests for RBAC

model/role.go, repository/rbac.go, repository/rbac_i_test.go, repository/role.go
=> RBAC tests

model/user.go, repository/user.go
=> Ensure deleted_at field is updated when executing a soft delete

mock/mockdb/account.go, model/user.go, model/user_test.go, repository/account.go, repository/account/account.go, repository/account_i_test.go, service/account_test.go
=> Add account tests

mock/mockdb/account.go, model/user.go, repository/account.go, repository/account_i_test.go, repository/auth/auth.go, service/auth_test.go
=> More tests for accountRepo

mock/mockdb/user.go, model/user.go, repository/user.go, repository/user/user.go, repository/user_i_test.go, service/user_test.go
=> userRepo List test

go.sum, mockgopg/build_insert.go, mockgopg/mock.go, mockgopg/orm.go, repository/account.go, repository/account_test.go
=> mock for go-pg insert

.gitignore, e2e/e2e.go, e2e/e2e_i_test.go, e2e/login_i_test.go, go.mod, go.sum, model/company.go, model/location.go, model/model.go, model/role.go, model/user.go, model/verification.go, testhelper/testhelper.go
=> Simple end-to-end test implementation

go.sum, mockgopg/mock.go, repository/account_i_test.go, repository/user_i_test.go
=> Complete user tests

e2e/e2e.go, e2e/e2e_i_test.go, e2e/login_i_test.go, go.mod, go.sum, main.go, manager/manager.go, repository/auth/auth.go, request/auth.go, route/route.go, service/auth.go, service/auth_test.go
=> First end-to-end test passes (login)

e2e/e2e_i_test.go, e2e/signupemail_i_test.go, e2e/signupmobile_i_test.go, mail/mail_interface.go, mobile/mobile_interface.go, mock/mail.go, repository/account.go, repository/auth/auth.go, request/signup.go, route/route.go, service/auth_test.go
=> end-to-end signup tests

go.mod
=> Remove unnecessary dependencies

cryptohelper/cryptohelper.go, e2e/mobile_i_test.go, repository/account.go, repository/auth/auth.go, request/signup.go, service/auth.go, service/auth_test.go
=> Passwordless mobile signup and login

manager/manager.go
=> When setting up superadmin user, do remember to set verified true too

e2e/e2e_i_test.go, e2e/login_i_test.go, e2e/signupemail_i_test.go, repository/auth/auth.go, service/auth.go
=> end-to-end test with refresh token to get a new JWT

e2e/e2e_i_test.go, go.sum, manager/manager.go, mock/secret.go, repository/account.go, repository/account/account.go, repository/account_i_test.go, repository/account_test.go, repository/auth/auth.go, repository/rbac_i_test.go, repository/user_i_test.go, route/route.go, secret/cryptorandom.go, secret/secret.go, secret/secret_interface.go, service/account_test.go, service/auth_test.go
=> Password as secret service

repository/account_i_test.go, repository/rbac_i_test.go, repository/user_i_test.go
=> Remove tmpdir to run integration tests

config/postgres.go
=> fix: validation fails when the database url is an empty string
